// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video_streaming.proto

package chrys_cloud_videostreaming_v1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnnotateRequest struct {
	DeviceName       string        `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	RemoteStreamId   string        `protobuf:"bytes,2,opt,name=remote_stream_id,json=remoteStreamId,proto3" json:"remote_stream_id,omitempty"`
	Type             string        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartTimestamp   int64         `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp     int64         `protobuf:"varint,5,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	ObjectType       string        `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId         string        `protobuf:"bytes,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectTrackingId string        `protobuf:"bytes,8,opt,name=object_tracking_id,json=objectTrackingId,proto3" json:"object_tracking_id,omitempty"`
	Confidence       float64       `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ObjectBoudingBox *BoudingBox   `protobuf:"bytes,10,opt,name=object_bouding_box,json=objectBoudingBox,proto3" json:"object_bouding_box,omitempty"`
	Location         *Location     `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	ObjectCoordinate *Coordinate   `protobuf:"bytes,12,opt,name=object_coordinate,json=objectCoordinate,proto3" json:"object_coordinate,omitempty"`
	Mask             []*Coordinate `protobuf:"bytes,13,rep,name=mask,proto3" json:"mask,omitempty"`
	ObjectSignature  []float64     `protobuf:"fixed64,14,rep,packed,name=object_signature,json=objectSignature,proto3" json:"object_signature,omitempty"`
	MlModel          string        `protobuf:"bytes,15,opt,name=ml_model,json=mlModel,proto3" json:"ml_model,omitempty"`
	MlModelVersion   string        `protobuf:"bytes,16,opt,name=ml_model_version,json=mlModelVersion,proto3" json:"ml_model_version,omitempty"`
	Width            int32         `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32         `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`
	IsKeyframe       bool          `protobuf:"varint,19,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`
	VideoType        string        `protobuf:"bytes,20,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`
	OffsetTimestamp  int64         `protobuf:"varint,21,opt,name=offset_timestamp,json=offsetTimestamp,proto3" json:"offset_timestamp,omitempty"`
	OffsetDuration   int64         `protobuf:"varint,22,opt,name=offset_duration,json=offsetDuration,proto3" json:"offset_duration,omitempty"`
	OffsetFrameId    int64         `protobuf:"varint,23,opt,name=offset_frame_id,json=offsetFrameId,proto3" json:"offset_frame_id,omitempty"`
	OffsetPacketId   int64         `protobuf:"varint,24,opt,name=offset_packet_id,json=offsetPacketId,proto3" json:"offset_packet_id,omitempty"`
	// extending the event message meta data (optional)
	CustomMeta_1         string   `protobuf:"bytes,25,opt,name=custom_meta_1,json=customMeta1,proto3" json:"custom_meta_1,omitempty"`
	CustomMeta_2         string   `protobuf:"bytes,26,opt,name=custom_meta_2,json=customMeta2,proto3" json:"custom_meta_2,omitempty"`
	CustomMeta_3         string   `protobuf:"bytes,27,opt,name=custom_meta_3,json=customMeta3,proto3" json:"custom_meta_3,omitempty"`
	CustomMeta_4         string   `protobuf:"bytes,28,opt,name=custom_meta_4,json=customMeta4,proto3" json:"custom_meta_4,omitempty"`
	CustomMeta_5         string   `protobuf:"bytes,29,opt,name=custom_meta_5,json=customMeta5,proto3" json:"custom_meta_5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnotateRequest) Reset()         { *m = AnnotateRequest{} }
func (m *AnnotateRequest) String() string { return proto.CompactTextString(m) }
func (*AnnotateRequest) ProtoMessage()    {}
func (*AnnotateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{0}
}

func (m *AnnotateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnotateRequest.Unmarshal(m, b)
}
func (m *AnnotateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnotateRequest.Marshal(b, m, deterministic)
}
func (m *AnnotateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnotateRequest.Merge(m, src)
}
func (m *AnnotateRequest) XXX_Size() int {
	return xxx_messageInfo_AnnotateRequest.Size(m)
}
func (m *AnnotateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnotateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnotateRequest proto.InternalMessageInfo

func (m *AnnotateRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *AnnotateRequest) GetRemoteStreamId() string {
	if m != nil {
		return m.RemoteStreamId
	}
	return ""
}

func (m *AnnotateRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnnotateRequest) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *AnnotateRequest) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *AnnotateRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *AnnotateRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *AnnotateRequest) GetObjectTrackingId() string {
	if m != nil {
		return m.ObjectTrackingId
	}
	return ""
}

func (m *AnnotateRequest) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *AnnotateRequest) GetObjectBoudingBox() *BoudingBox {
	if m != nil {
		return m.ObjectBoudingBox
	}
	return nil
}

func (m *AnnotateRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *AnnotateRequest) GetObjectCoordinate() *Coordinate {
	if m != nil {
		return m.ObjectCoordinate
	}
	return nil
}

func (m *AnnotateRequest) GetMask() []*Coordinate {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *AnnotateRequest) GetObjectSignature() []float64 {
	if m != nil {
		return m.ObjectSignature
	}
	return nil
}

func (m *AnnotateRequest) GetMlModel() string {
	if m != nil {
		return m.MlModel
	}
	return ""
}

func (m *AnnotateRequest) GetMlModelVersion() string {
	if m != nil {
		return m.MlModelVersion
	}
	return ""
}

func (m *AnnotateRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AnnotateRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AnnotateRequest) GetIsKeyframe() bool {
	if m != nil {
		return m.IsKeyframe
	}
	return false
}

func (m *AnnotateRequest) GetVideoType() string {
	if m != nil {
		return m.VideoType
	}
	return ""
}

func (m *AnnotateRequest) GetOffsetTimestamp() int64 {
	if m != nil {
		return m.OffsetTimestamp
	}
	return 0
}

func (m *AnnotateRequest) GetOffsetDuration() int64 {
	if m != nil {
		return m.OffsetDuration
	}
	return 0
}

func (m *AnnotateRequest) GetOffsetFrameId() int64 {
	if m != nil {
		return m.OffsetFrameId
	}
	return 0
}

func (m *AnnotateRequest) GetOffsetPacketId() int64 {
	if m != nil {
		return m.OffsetPacketId
	}
	return 0
}

func (m *AnnotateRequest) GetCustomMeta_1() string {
	if m != nil {
		return m.CustomMeta_1
	}
	return ""
}

func (m *AnnotateRequest) GetCustomMeta_2() string {
	if m != nil {
		return m.CustomMeta_2
	}
	return ""
}

func (m *AnnotateRequest) GetCustomMeta_3() string {
	if m != nil {
		return m.CustomMeta_3
	}
	return ""
}

func (m *AnnotateRequest) GetCustomMeta_4() string {
	if m != nil {
		return m.CustomMeta_4
	}
	return ""
}

func (m *AnnotateRequest) GetCustomMeta_5() string {
	if m != nil {
		return m.CustomMeta_5
	}
	return ""
}

type AnnotateResponse struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	RemoteStreamId       string   `protobuf:"bytes,2,opt,name=remote_stream_id,json=remoteStreamId,proto3" json:"remote_stream_id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnotateResponse) Reset()         { *m = AnnotateResponse{} }
func (m *AnnotateResponse) String() string { return proto.CompactTextString(m) }
func (*AnnotateResponse) ProtoMessage()    {}
func (*AnnotateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{1}
}

func (m *AnnotateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnotateResponse.Unmarshal(m, b)
}
func (m *AnnotateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnotateResponse.Marshal(b, m, deterministic)
}
func (m *AnnotateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnotateResponse.Merge(m, src)
}
func (m *AnnotateResponse) XXX_Size() int {
	return xxx_messageInfo_AnnotateResponse.Size(m)
}
func (m *AnnotateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnotateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnotateResponse proto.InternalMessageInfo

func (m *AnnotateResponse) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *AnnotateResponse) GetRemoteStreamId() string {
	if m != nil {
		return m.RemoteStreamId
	}
	return ""
}

func (m *AnnotateResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnnotateResponse) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

type Location struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Coordinate struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{3}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Coordinate) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type BoudingBox struct {
	Top                  int32    `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	Left                 int32    `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoudingBox) Reset()         { *m = BoudingBox{} }
func (m *BoudingBox) String() string { return proto.CompactTextString(m) }
func (*BoudingBox) ProtoMessage()    {}
func (*BoudingBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{4}
}

func (m *BoudingBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoudingBox.Unmarshal(m, b)
}
func (m *BoudingBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoudingBox.Marshal(b, m, deterministic)
}
func (m *BoudingBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoudingBox.Merge(m, src)
}
func (m *BoudingBox) XXX_Size() int {
	return xxx_messageInfo_BoudingBox.Size(m)
}
func (m *BoudingBox) XXX_DiscardUnknown() {
	xxx_messageInfo_BoudingBox.DiscardUnknown(m)
}

var xxx_messageInfo_BoudingBox proto.InternalMessageInfo

func (m *BoudingBox) GetTop() int32 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *BoudingBox) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *BoudingBox) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *BoudingBox) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ShapeProto struct {
	Dim                  []*ShapeProto_Dim `protobuf:"bytes,2,rep,name=dim,proto3" json:"dim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShapeProto) Reset()         { *m = ShapeProto{} }
func (m *ShapeProto) String() string { return proto.CompactTextString(m) }
func (*ShapeProto) ProtoMessage()    {}
func (*ShapeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{5}
}

func (m *ShapeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShapeProto.Unmarshal(m, b)
}
func (m *ShapeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShapeProto.Marshal(b, m, deterministic)
}
func (m *ShapeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShapeProto.Merge(m, src)
}
func (m *ShapeProto) XXX_Size() int {
	return xxx_messageInfo_ShapeProto.Size(m)
}
func (m *ShapeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ShapeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ShapeProto proto.InternalMessageInfo

func (m *ShapeProto) GetDim() []*ShapeProto_Dim {
	if m != nil {
		return m.Dim
	}
	return nil
}

type ShapeProto_Dim struct {
	// Size of image in that dimension (-1 means unknown dimension)
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// optional name of image dimension
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShapeProto_Dim) Reset()         { *m = ShapeProto_Dim{} }
func (m *ShapeProto_Dim) String() string { return proto.CompactTextString(m) }
func (*ShapeProto_Dim) ProtoMessage()    {}
func (*ShapeProto_Dim) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{5, 0}
}

func (m *ShapeProto_Dim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShapeProto_Dim.Unmarshal(m, b)
}
func (m *ShapeProto_Dim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShapeProto_Dim.Marshal(b, m, deterministic)
}
func (m *ShapeProto_Dim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShapeProto_Dim.Merge(m, src)
}
func (m *ShapeProto_Dim) XXX_Size() int {
	return xxx_messageInfo_ShapeProto_Dim.Size(m)
}
func (m *ShapeProto_Dim) XXX_DiscardUnknown() {
	xxx_messageInfo_ShapeProto_Dim.DiscardUnknown(m)
}

var xxx_messageInfo_ShapeProto_Dim proto.InternalMessageInfo

func (m *ShapeProto_Dim) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ShapeProto_Dim) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VideoFrame struct {
	Width                int64       `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64       `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            int64       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsKeyframe           bool        `protobuf:"varint,5,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`
	Pts                  int64       `protobuf:"varint,6,opt,name=pts,proto3" json:"pts,omitempty"`
	Dts                  int64       `protobuf:"varint,7,opt,name=dts,proto3" json:"dts,omitempty"`
	FrameType            string      `protobuf:"bytes,8,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	IsCorrupt            bool        `protobuf:"varint,9,opt,name=is_corrupt,json=isCorrupt,proto3" json:"is_corrupt,omitempty"`
	TimeBase             float64     `protobuf:"fixed64,10,opt,name=time_base,json=timeBase,proto3" json:"time_base,omitempty"`
	Shape                *ShapeProto `protobuf:"bytes,11,opt,name=shape,proto3" json:"shape,omitempty"`
	DeviceId             string      `protobuf:"bytes,12,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Packet               int64       `protobuf:"varint,13,opt,name=packet,proto3" json:"packet,omitempty"`
	Keyframe             int64       `protobuf:"varint,14,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VideoFrame) Reset()         { *m = VideoFrame{} }
func (m *VideoFrame) String() string { return proto.CompactTextString(m) }
func (*VideoFrame) ProtoMessage()    {}
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{6}
}

func (m *VideoFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFrame.Unmarshal(m, b)
}
func (m *VideoFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFrame.Marshal(b, m, deterministic)
}
func (m *VideoFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFrame.Merge(m, src)
}
func (m *VideoFrame) XXX_Size() int {
	return xxx_messageInfo_VideoFrame.Size(m)
}
func (m *VideoFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFrame.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFrame proto.InternalMessageInfo

func (m *VideoFrame) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *VideoFrame) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VideoFrame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VideoFrame) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VideoFrame) GetIsKeyframe() bool {
	if m != nil {
		return m.IsKeyframe
	}
	return false
}

func (m *VideoFrame) GetPts() int64 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *VideoFrame) GetDts() int64 {
	if m != nil {
		return m.Dts
	}
	return 0
}

func (m *VideoFrame) GetFrameType() string {
	if m != nil {
		return m.FrameType
	}
	return ""
}

func (m *VideoFrame) GetIsCorrupt() bool {
	if m != nil {
		return m.IsCorrupt
	}
	return false
}

func (m *VideoFrame) GetTimeBase() float64 {
	if m != nil {
		return m.TimeBase
	}
	return 0
}

func (m *VideoFrame) GetShape() *ShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *VideoFrame) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *VideoFrame) GetPacket() int64 {
	if m != nil {
		return m.Packet
	}
	return 0
}

func (m *VideoFrame) GetKeyframe() int64 {
	if m != nil {
		return m.Keyframe
	}
	return 0
}

type VideoFrameRequest struct {
	KeyFrameOnly         bool     `protobuf:"varint,1,opt,name=key_frame_only,json=keyFrameOnly,proto3" json:"key_frame_only,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFrameRequest) Reset()         { *m = VideoFrameRequest{} }
func (m *VideoFrameRequest) String() string { return proto.CompactTextString(m) }
func (*VideoFrameRequest) ProtoMessage()    {}
func (*VideoFrameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{7}
}

func (m *VideoFrameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFrameRequest.Unmarshal(m, b)
}
func (m *VideoFrameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFrameRequest.Marshal(b, m, deterministic)
}
func (m *VideoFrameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFrameRequest.Merge(m, src)
}
func (m *VideoFrameRequest) XXX_Size() int {
	return xxx_messageInfo_VideoFrameRequest.Size(m)
}
func (m *VideoFrameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFrameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFrameRequest proto.InternalMessageInfo

func (m *VideoFrameRequest) GetKeyFrameOnly() bool {
	if m != nil {
		return m.KeyFrameOnly
	}
	return false
}

func (m *VideoFrameRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ListStream struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FailingStreak        int64    `protobuf:"varint,3,opt,name=failing_streak,json=failingStreak,proto3" json:"failing_streak,omitempty"`
	HealthStatus         string   `protobuf:"bytes,4,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	Dead                 bool     `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	ExitCode             int64    `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Pid                  int32    `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Running              bool     `protobuf:"varint,8,opt,name=running,proto3" json:"running,omitempty"`
	Paused               bool     `protobuf:"varint,9,opt,name=paused,proto3" json:"paused,omitempty"`
	Restarting           bool     `protobuf:"varint,10,opt,name=restarting,proto3" json:"restarting,omitempty"`
	Oomkilled            bool     `protobuf:"varint,11,opt,name=oomkilled,proto3" json:"oomkilled,omitempty"`
	Error                string   `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStream) Reset()         { *m = ListStream{} }
func (m *ListStream) String() string { return proto.CompactTextString(m) }
func (*ListStream) ProtoMessage()    {}
func (*ListStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{8}
}

func (m *ListStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStream.Unmarshal(m, b)
}
func (m *ListStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStream.Marshal(b, m, deterministic)
}
func (m *ListStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStream.Merge(m, src)
}
func (m *ListStream) XXX_Size() int {
	return xxx_messageInfo_ListStream.Size(m)
}
func (m *ListStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStream.DiscardUnknown(m)
}

var xxx_messageInfo_ListStream proto.InternalMessageInfo

func (m *ListStream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListStream) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListStream) GetFailingStreak() int64 {
	if m != nil {
		return m.FailingStreak
	}
	return 0
}

func (m *ListStream) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

func (m *ListStream) GetDead() bool {
	if m != nil {
		return m.Dead
	}
	return false
}

func (m *ListStream) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *ListStream) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ListStream) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *ListStream) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *ListStream) GetRestarting() bool {
	if m != nil {
		return m.Restarting
	}
	return false
}

func (m *ListStream) GetOomkilled() bool {
	if m != nil {
		return m.Oomkilled
	}
	return false
}

func (m *ListStream) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStreamRequest) Reset()         { *m = ListStreamRequest{} }
func (m *ListStreamRequest) String() string { return proto.CompactTextString(m) }
func (*ListStreamRequest) ProtoMessage()    {}
func (*ListStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{9}
}

func (m *ListStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStreamRequest.Unmarshal(m, b)
}
func (m *ListStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStreamRequest.Marshal(b, m, deterministic)
}
func (m *ListStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStreamRequest.Merge(m, src)
}
func (m *ListStreamRequest) XXX_Size() int {
	return xxx_messageInfo_ListStreamRequest.Size(m)
}
func (m *ListStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStreamRequest proto.InternalMessageInfo

type StartProxyRequest struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StoreVideo           bool     `protobuf:"varint,2,opt,name=store_video,json=storeVideo,proto3" json:"store_video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartProxyRequest) Reset()         { *m = StartProxyRequest{} }
func (m *StartProxyRequest) String() string { return proto.CompactTextString(m) }
func (*StartProxyRequest) ProtoMessage()    {}
func (*StartProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{10}
}

func (m *StartProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartProxyRequest.Unmarshal(m, b)
}
func (m *StartProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartProxyRequest.Marshal(b, m, deterministic)
}
func (m *StartProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartProxyRequest.Merge(m, src)
}
func (m *StartProxyRequest) XXX_Size() int {
	return xxx_messageInfo_StartProxyRequest.Size(m)
}
func (m *StartProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartProxyRequest proto.InternalMessageInfo

func (m *StartProxyRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *StartProxyRequest) GetStoreVideo() bool {
	if m != nil {
		return m.StoreVideo
	}
	return false
}

type StopProxyRequest struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopProxyRequest) Reset()         { *m = StopProxyRequest{} }
func (m *StopProxyRequest) String() string { return proto.CompactTextString(m) }
func (*StopProxyRequest) ProtoMessage()    {}
func (*StopProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{11}
}

func (m *StopProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopProxyRequest.Unmarshal(m, b)
}
func (m *StopProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopProxyRequest.Marshal(b, m, deterministic)
}
func (m *StopProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopProxyRequest.Merge(m, src)
}
func (m *StopProxyRequest) XXX_Size() int {
	return xxx_messageInfo_StopProxyRequest.Size(m)
}
func (m *StopProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopProxyRequest proto.InternalMessageInfo

func (m *StopProxyRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ProxyResponse struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ProxyStream          bool     `protobuf:"varint,2,opt,name=proxy_stream,json=proxyStream,proto3" json:"proxy_stream,omitempty"`
	StoreVideo           bool     `protobuf:"varint,3,opt,name=store_video,json=storeVideo,proto3" json:"store_video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyResponse) Reset()         { *m = ProxyResponse{} }
func (m *ProxyResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyResponse) ProtoMessage()    {}
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d12c9ba8c5e732, []int{12}
}

func (m *ProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyResponse.Unmarshal(m, b)
}
func (m *ProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyResponse.Marshal(b, m, deterministic)
}
func (m *ProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyResponse.Merge(m, src)
}
func (m *ProxyResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyResponse.Size(m)
}
func (m *ProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyResponse proto.InternalMessageInfo

func (m *ProxyResponse) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ProxyResponse) GetProxyStream() bool {
	if m != nil {
		return m.ProxyStream
	}
	return false
}

func (m *ProxyResponse) GetStoreVideo() bool {
	if m != nil {
		return m.StoreVideo
	}
	return false
}

func init() {
	proto.RegisterType((*AnnotateRequest)(nil), "chrys.cloud.videostreaming.v1beta1.AnnotateRequest")
	proto.RegisterType((*AnnotateResponse)(nil), "chrys.cloud.videostreaming.v1beta1.AnnotateResponse")
	proto.RegisterType((*Location)(nil), "chrys.cloud.videostreaming.v1beta1.Location")
	proto.RegisterType((*Coordinate)(nil), "chrys.cloud.videostreaming.v1beta1.Coordinate")
	proto.RegisterType((*BoudingBox)(nil), "chrys.cloud.videostreaming.v1beta1.BoudingBox")
	proto.RegisterType((*ShapeProto)(nil), "chrys.cloud.videostreaming.v1beta1.ShapeProto")
	proto.RegisterType((*ShapeProto_Dim)(nil), "chrys.cloud.videostreaming.v1beta1.ShapeProto.Dim")
	proto.RegisterType((*VideoFrame)(nil), "chrys.cloud.videostreaming.v1beta1.VideoFrame")
	proto.RegisterType((*VideoFrameRequest)(nil), "chrys.cloud.videostreaming.v1beta1.VideoFrameRequest")
	proto.RegisterType((*ListStream)(nil), "chrys.cloud.videostreaming.v1beta1.ListStream")
	proto.RegisterType((*ListStreamRequest)(nil), "chrys.cloud.videostreaming.v1beta1.ListStreamRequest")
	proto.RegisterType((*StartProxyRequest)(nil), "chrys.cloud.videostreaming.v1beta1.StartProxyRequest")
	proto.RegisterType((*StopProxyRequest)(nil), "chrys.cloud.videostreaming.v1beta1.StopProxyRequest")
	proto.RegisterType((*ProxyResponse)(nil), "chrys.cloud.videostreaming.v1beta1.ProxyResponse")
}

func init() {
	proto.RegisterFile("video_streaming.proto", fileDescriptor_f3d12c9ba8c5e732)
}

var fileDescriptor_f3d12c9ba8c5e732 = []byte{
	// 1279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xae, 0x62, 0xbb, 0x91, 0x8f, 0x1d, 0xc7, 0xd9, 0xfe, 0xa0, 0xba, 0x2d, 0x14, 0xf1, 0x17,
	0x66, 0x8a, 0x21, 0x3f, 0xe5, 0x9e, 0xb4, 0xc3, 0xd0, 0xa1, 0x85, 0x22, 0x77, 0x7a, 0x03, 0x33,
	0x42, 0xb6, 0xd6, 0xb1, 0xb0, 0xa4, 0x35, 0xd2, 0x3a, 0xb5, 0x73, 0xc3, 0xf0, 0x1a, 0xdc, 0xf2,
	0x38, 0x0c, 0x8f, 0xc2, 0x3b, 0x70, 0xf6, 0xec, 0xca, 0x72, 0x14, 0x06, 0x9c, 0x5e, 0x71, 0xb7,
	0xfb, 0xed, 0x77, 0x7e, 0xb4, 0xe7, 0x3b, 0x67, 0x6d, 0xb8, 0x75, 0x16, 0x85, 0x5c, 0xf8, 0xb9,
	0xcc, 0x78, 0x90, 0x44, 0xe9, 0x69, 0x7f, 0x96, 0x09, 0x29, 0x98, 0x3b, 0x9a, 0x64, 0xcb, 0xbc,
	0x3f, 0x8a, 0xc5, 0x3c, 0xec, 0x13, 0xa5, 0x64, 0x9c, 0x1d, 0x0c, 0xb9, 0x0c, 0x0e, 0xdc, 0x3f,
	0x9a, 0xb0, 0xfb, 0x45, 0x9a, 0x0a, 0x19, 0x48, 0xee, 0xf1, 0x9f, 0xe7, 0x3c, 0x97, 0xec, 0x1d,
	0x68, 0x85, 0xfc, 0x2c, 0x1a, 0x71, 0x3f, 0x0d, 0x12, 0xee, 0x58, 0x0f, 0xac, 0xfd, 0xa6, 0x07,
	0x1a, 0xfa, 0x06, 0x11, 0xb6, 0x0f, 0xdd, 0x8c, 0x27, 0x42, 0x72, 0x13, 0xd2, 0x8f, 0x42, 0x67,
	0x8b, 0x58, 0x1d, 0x8d, 0x0f, 0x08, 0x7e, 0x1a, 0x32, 0x06, 0x75, 0xb9, 0x9c, 0x71, 0xa7, 0x46,
	0xa7, 0xb4, 0x66, 0x1f, 0xc1, 0x6e, 0x2e, 0x83, 0x4c, 0xfa, 0x32, 0x4a, 0x30, 0x5c, 0x90, 0xcc,
	0x9c, 0x3a, 0x1e, 0xd7, 0xbc, 0x0e, 0xc1, 0x2f, 0x0b, 0x94, 0xbd, 0x07, 0x3b, 0x3c, 0x0d, 0xd7,
	0x68, 0x0d, 0xa2, 0xb5, 0x11, 0x2c, 0x49, 0x98, 0xac, 0x18, 0xfe, 0xc4, 0x47, 0xe8, 0x4e, 0x05,
	0xba, 0xae, 0x93, 0xd5, 0xd0, 0x4b, 0x15, 0xee, 0x2e, 0x34, 0x0d, 0x01, 0xb3, 0xdc, 0xa6, 0x63,
	0x5b, 0x03, 0x98, 0xdf, 0x43, 0x60, 0x85, 0x75, 0x16, 0x8c, 0xa6, 0x78, 0x33, 0x8a, 0x65, 0x13,
	0xab, 0x6b, 0x9c, 0x98, 0x03, 0x64, 0xbf, 0x0d, 0x30, 0x12, 0xe9, 0x18, 0x6f, 0x32, 0x1d, 0x71,
	0xa7, 0x89, 0x2c, 0xcb, 0x5b, 0x43, 0xd8, 0x0f, 0x2b, 0x6f, 0x43, 0xbc, 0x72, 0xe5, 0x6c, 0x28,
	0x16, 0x0e, 0x20, 0xaf, 0x75, 0xd8, 0xef, 0xff, 0x77, 0x35, 0xfa, 0x27, 0xda, 0xec, 0x44, 0x2c,
	0x8a, 0xe8, 0x25, 0xc2, 0xbe, 0x02, 0x3b, 0x16, 0xa3, 0x40, 0x46, 0x22, 0x75, 0x5a, 0xe4, 0xf3,
	0xe1, 0x26, 0x3e, 0x9f, 0x19, 0x1b, 0x6f, 0x65, 0xcd, 0xbe, 0x87, 0x3d, 0x93, 0xe7, 0x48, 0x88,
	0x0c, 0xfd, 0x63, 0xf1, 0x9d, 0xf6, 0xe6, 0x69, 0x3e, 0x5e, 0x59, 0x15, 0x69, 0x96, 0x08, 0x3b,
	0x81, 0x7a, 0x12, 0xe4, 0x53, 0x67, 0xe7, 0x41, 0xed, 0x0d, 0xfc, 0x91, 0x2d, 0xfb, 0x18, 0x8c,
	0x5f, 0x3f, 0x8f, 0x4e, 0x11, 0x9f, 0x67, 0xdc, 0xe9, 0xa0, 0x3f, 0xcb, 0xdb, 0xd5, 0xf8, 0xa0,
	0x80, 0xd9, 0x1d, 0xb0, 0x93, 0xd8, 0x4f, 0x44, 0xc8, 0x63, 0x67, 0x97, 0xea, 0xb6, 0x9d, 0xc4,
	0xcf, 0xd5, 0x56, 0xc9, 0xb4, 0x38, 0xf2, 0xcf, 0x78, 0x96, 0xab, 0x8b, 0xeb, 0x6a, 0x99, 0x1a,
	0xca, 0x2b, 0x8d, 0xb2, 0x9b, 0xd0, 0x78, 0x1d, 0x85, 0x72, 0xe2, 0xec, 0xe1, 0x71, 0xc3, 0xd3,
	0x1b, 0x76, 0x1b, 0xae, 0x4f, 0x78, 0x74, 0x3a, 0x91, 0x0e, 0x23, 0xd8, 0xec, 0x94, 0xe4, 0xa2,
	0xdc, 0x9f, 0xf2, 0xe5, 0x38, 0x53, 0xfd, 0x71, 0x03, 0x0f, 0x6d, 0x0f, 0xa2, 0xfc, 0x6b, 0x83,
	0xb0, 0xfb, 0x00, 0xba, 0x23, 0x49, 0x92, 0x37, 0x29, 0x64, 0x93, 0x10, 0x52, 0xa4, 0xfa, 0xba,
	0xf1, 0x38, 0xe7, 0xeb, 0x1d, 0x70, 0x8b, 0xa4, 0xbd, 0xab, 0xf1, 0x52, 0xdd, 0xd8, 0x2b, 0x86,
	0x1a, 0xce, 0x33, 0x5d, 0xfa, 0xdb, 0xba, 0x57, 0x34, 0xfc, 0xc4, 0xa0, 0xec, 0xc3, 0x15, 0x91,
	0x52, 0x50, 0x2a, 0x7e, 0x8b, 0x88, 0x3b, 0x1a, 0xfe, 0x52, 0xa1, 0x28, 0xe1, 0xfd, 0x55, 0xec,
	0x19, 0xca, 0x9a, 0x53, 0x53, 0x38, 0xeb, 0x1e, 0x5f, 0x10, 0x8c, 0x4c, 0x17, 0x76, 0x46, 0xf3,
	0x5c, 0x8a, 0xc4, 0x4f, 0xb0, 0x48, 0xfe, 0x81, 0x73, 0x87, 0xbe, 0xa3, 0xa5, 0xc1, 0xe7, 0xaa,
	0x70, 0x55, 0xce, 0xa1, 0xd3, 0xab, 0x72, 0x0e, 0xab, 0x9c, 0x23, 0xe7, 0x6e, 0x95, 0x73, 0x54,
	0xe5, 0x1c, 0x3b, 0xf7, 0xaa, 0x9c, 0xe3, 0x2a, 0xe7, 0x91, 0x73, 0xbf, 0xca, 0x79, 0xe4, 0xfe,
	0x66, 0x41, 0xb7, 0x9c, 0x66, 0xf9, 0x4c, 0xa4, 0x39, 0xff, 0xbf, 0x8c, 0x33, 0xb7, 0x0f, 0x76,
	0xd1, 0x8b, 0xac, 0x0b, 0xb5, 0x38, 0x90, 0x94, 0x8b, 0xe5, 0xa9, 0x25, 0x21, 0x58, 0xdd, 0x2d,
	0x83, 0x88, 0xd4, 0xfd, 0x1c, 0x60, 0xad, 0xad, 0xda, 0x60, 0x2d, 0x0c, 0xdf, 0x5a, 0xa8, 0xdd,
	0xd2, 0x70, 0xad, 0xa5, 0xda, 0x9d, 0x53, 0x4e, 0xb8, 0x3b, 0x77, 0x7f, 0x04, 0x58, 0x9b, 0x1a,
	0xe8, 0x57, 0x8a, 0x19, 0x59, 0x36, 0x3c, 0xb5, 0x54, 0x1f, 0x11, 0xf3, 0xb1, 0x24, 0xf3, 0x86,
	0x47, 0xeb, 0xb2, 0x01, 0x6a, 0xff, 0xdc, 0x00, 0xf5, 0xf5, 0x06, 0x70, 0x7f, 0xb5, 0x00, 0x06,
	0x93, 0x60, 0xc6, 0x5f, 0xd0, 0x3b, 0xf3, 0x04, 0x6a, 0x61, 0x94, 0xa0, 0x3f, 0xd5, 0xf0, 0x87,
	0x9b, 0x34, 0x7c, 0x69, 0xdc, 0x7f, 0x12, 0x25, 0x9e, 0x32, 0xef, 0x7d, 0x02, 0x35, 0x5c, 0xab,
	0xec, 0xf2, 0xe8, 0x5c, 0x97, 0xa9, 0xe6, 0xd1, 0x5a, 0x61, 0x54, 0x3a, 0x5d, 0x14, 0x5a, 0xbb,
	0xbf, 0xd7, 0x00, 0x5e, 0x29, 0xef, 0xa4, 0xec, 0xf2, 0x03, 0xb4, 0xdd, 0xa5, 0x0f, 0xd8, 0x22,
	0xb8, 0xe8, 0x60, 0x74, 0x18, 0x06, 0x32, 0xa0, 0xaf, 0x6d, 0x7b, 0xb4, 0x66, 0xf7, 0xa0, 0x59,
	0xad, 0x60, 0x09, 0x54, 0x7b, 0xbe, 0x71, 0xa9, 0xe7, 0xf1, 0x9e, 0x67, 0x32, 0xa7, 0xf7, 0xa7,
	0xe6, 0xa9, 0xa5, 0x42, 0x42, 0x44, 0xb6, 0x35, 0x82, 0x4b, 0x35, 0x17, 0x74, 0x77, 0x92, 0x88,
	0xf4, 0x2b, 0xd3, 0x24, 0x84, 0xe6, 0x02, 0x1e, 0x63, 0x8c, 0x91, 0xc8, 0xb2, 0xf9, 0x4c, 0xd2,
	0xf3, 0x62, 0x7b, 0xcd, 0x28, 0x7f, 0xac, 0x01, 0xf5, 0x90, 0xa9, 0x7c, 0xfc, 0x61, 0x90, 0x73,
	0x7a, 0x54, 0x2c, 0xcf, 0x56, 0xc0, 0x09, 0xee, 0xb1, 0x06, 0x8d, 0x5c, 0x5d, 0xaa, 0x79, 0x19,
	0xfa, 0x57, 0xab, 0x82, 0xa7, 0x8d, 0x55, 0x08, 0xd3, 0x2a, 0xd8, 0x02, 0x6d, 0xfd, 0x56, 0x6a,
	0x00, 0xc5, 0x8f, 0x97, 0xa9, 0x67, 0x06, 0x8e, 0x76, 0xba, 0x4c, 0xbd, 0x63, 0x3d, 0xb0, 0x57,
	0xf7, 0xd2, 0xa1, 0x93, 0xd5, 0xde, 0x7d, 0x05, 0x7b, 0x65, 0x91, 0x8a, 0xdf, 0x17, 0xef, 0x43,
	0x07, 0x09, 0x66, 0x50, 0x89, 0x34, 0x5e, 0x52, 0xd1, 0x6c, 0xaf, 0x8d, 0x28, 0x11, 0xbf, 0x45,
	0xec, 0x62, 0x2e, 0x5b, 0x17, 0x73, 0x71, 0xff, 0xdc, 0x02, 0x78, 0x16, 0xe5, 0x52, 0x77, 0xe6,
	0x4a, 0x20, 0x56, 0x29, 0x10, 0x95, 0x2e, 0x96, 0x4e, 0xce, 0x73, 0x63, 0x6c, 0x76, 0xec, 0x03,
	0xe8, 0x8c, 0x83, 0x28, 0x56, 0xaf, 0x33, 0x5d, 0xc9, 0x94, 0x54, 0x80, 0x83, 0xd2, 0xa0, 0xe4,
	0x72, 0xaa, 0x7e, 0x7c, 0x4c, 0x78, 0x10, 0xcb, 0x89, 0x6f, 0xbc, 0xd4, 0xc9, 0x4b, 0x5b, 0x83,
	0x03, 0xed, 0x4b, 0xe9, 0x88, 0x07, 0xa1, 0x91, 0x03, 0xad, 0x55, 0xde, 0x7c, 0x11, 0xa9, 0xa7,
	0x35, 0xe4, 0x46, 0x0e, 0xb6, 0x02, 0x1e, 0xe3, 0x9e, 0x54, 0x62, 0x7e, 0x86, 0x60, 0x37, 0xe2,
	0x92, 0x39, 0xb0, 0x9d, 0xcd, 0xd3, 0x14, 0x03, 0x93, 0x20, 0x6c, 0xaf, 0xd8, 0xea, 0xfb, 0x9e,
	0xe7, 0x3c, 0x34, 0x52, 0x30, 0x3b, 0xf5, 0x2b, 0x24, 0xe3, 0x34, 0x5b, 0x94, 0x11, 0x68, 0x25,
	0x96, 0x88, 0x12, 0xb2, 0x10, 0xc9, 0x34, 0x8a, 0x63, 0x34, 0x6d, 0x69, 0x15, 0xad, 0x00, 0xd5,
	0x28, 0x3c, 0xcb, 0x44, 0x66, 0xca, 0xab, 0x37, 0xee, 0x0d, 0xd8, 0x2b, 0xaf, 0xd3, 0xd4, 0xc9,
	0xfd, 0x0e, 0xf6, 0x06, 0xca, 0x29, 0x4a, 0x64, 0xb1, 0x2c, 0x8a, 0x77, 0xa1, 0x2c, 0x56, 0x45,
	0x22, 0xd8, 0x25, 0x38, 0x8c, 0x33, 0xee, 0x93, 0xe2, 0xe8, 0xe2, 0x31, 0x37, 0x82, 0x48, 0x06,
	0xee, 0xa7, 0xd0, 0x1d, 0xe0, 0x0c, 0xda, 0xd8, 0xa3, 0x3b, 0x83, 0x1d, 0x43, 0x36, 0xd3, 0xfc,
	0x5f, 0xe3, 0xbf, 0x0b, 0xed, 0x99, 0x62, 0x9b, 0x41, 0x6e, 0x12, 0x68, 0x11, 0x66, 0xa4, 0x52,
	0x49, 0xb1, 0x56, 0x4d, 0xf1, 0xf0, 0xaf, 0x3a, 0x34, 0x9e, 0x26, 0xc1, 0x29, 0x67, 0xbf, 0x40,
	0x97, 0xa0, 0x67, 0x38, 0x7f, 0x73, 0xa9, 0xb1, 0x47, 0x9b, 0x34, 0xd6, 0x25, 0xc9, 0xf7, 0xfa,
	0x57, 0x33, 0x73, 0xaf, 0xed, 0x5b, 0x9f, 0x59, 0x6c, 0x01, 0xad, 0xb2, 0x2a, 0xf9, 0x66, 0xb1,
	0x2f, 0x95, 0x71, 0xb3, 0xd8, 0xa5, 0x99, 0x7b, 0x8d, 0x22, 0x43, 0x59, 0xfa, 0xcd, 0x02, 0x5f,
	0x92, 0x4a, 0xef, 0x60, 0x13, 0xb3, 0x0b, 0xd5, 0x75, 0xaf, 0xb1, 0x33, 0x68, 0xae, 0x14, 0xc2,
	0x8e, 0x37, 0x0b, 0x7c, 0x51, 0x50, 0x6f, 0x16, 0xf7, 0x35, 0xd8, 0xc5, 0x2f, 0x07, 0x76, 0xb4,
	0x89, 0x83, 0xca, 0xbf, 0xa6, 0xde, 0xf1, 0xd5, 0x8c, 0x8a, 0xc0, 0xc3, 0xeb, 0xf4, 0x67, 0xed,
	0xe8, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x04, 0x10, 0xa0, 0xc5, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImageClient is the client API for Image service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageClient interface {
	VideoLatestImage(ctx context.Context, opts ...grpc.CallOption) (Image_VideoLatestImageClient, error)
	ListStreams(ctx context.Context, in *ListStreamRequest, opts ...grpc.CallOption) (Image_ListStreamsClient, error)
	StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
	StopProxy(ctx context.Context, in *StopProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
	Annotate(ctx context.Context, in *AnnotateRequest, opts ...grpc.CallOption) (*AnnotateResponse, error)
}

type imageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClient(cc grpc.ClientConnInterface) ImageClient {
	return &imageClient{cc}
}

func (c *imageClient) VideoLatestImage(ctx context.Context, opts ...grpc.CallOption) (Image_VideoLatestImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Image_serviceDesc.Streams[0], "/chrys.cloud.videostreaming.v1beta1.Image/VideoLatestImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageVideoLatestImageClient{stream}
	return x, nil
}

type Image_VideoLatestImageClient interface {
	Send(*VideoFrameRequest) error
	Recv() (*VideoFrame, error)
	grpc.ClientStream
}

type imageVideoLatestImageClient struct {
	grpc.ClientStream
}

func (x *imageVideoLatestImageClient) Send(m *VideoFrameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageVideoLatestImageClient) Recv() (*VideoFrame, error) {
	m := new(VideoFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) ListStreams(ctx context.Context, in *ListStreamRequest, opts ...grpc.CallOption) (Image_ListStreamsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Image_serviceDesc.Streams[1], "/chrys.cloud.videostreaming.v1beta1.Image/ListStreams", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageListStreamsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_ListStreamsClient interface {
	Recv() (*ListStream, error)
	grpc.ClientStream
}

type imageListStreamsClient struct {
	grpc.ClientStream
}

func (x *imageListStreamsClient) Recv() (*ListStream, error) {
	m := new(ListStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, "/chrys.cloud.videostreaming.v1beta1.Image/StartProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) StopProxy(ctx context.Context, in *StopProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, "/chrys.cloud.videostreaming.v1beta1.Image/StopProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) Annotate(ctx context.Context, in *AnnotateRequest, opts ...grpc.CallOption) (*AnnotateResponse, error) {
	out := new(AnnotateResponse)
	err := c.cc.Invoke(ctx, "/chrys.cloud.videostreaming.v1beta1.Image/Annotate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServer is the server API for Image service.
type ImageServer interface {
	VideoLatestImage(Image_VideoLatestImageServer) error
	ListStreams(*ListStreamRequest, Image_ListStreamsServer) error
	StartProxy(context.Context, *StartProxyRequest) (*ProxyResponse, error)
	StopProxy(context.Context, *StopProxyRequest) (*ProxyResponse, error)
	Annotate(context.Context, *AnnotateRequest) (*AnnotateResponse, error)
}

// UnimplementedImageServer can be embedded to have forward compatible implementations.
type UnimplementedImageServer struct {
}

func (*UnimplementedImageServer) VideoLatestImage(srv Image_VideoLatestImageServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoLatestImage not implemented")
}
func (*UnimplementedImageServer) ListStreams(req *ListStreamRequest, srv Image_ListStreamsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (*UnimplementedImageServer) StartProxy(ctx context.Context, req *StartProxyRequest) (*ProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProxy not implemented")
}
func (*UnimplementedImageServer) StopProxy(ctx context.Context, req *StopProxyRequest) (*ProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProxy not implemented")
}
func (*UnimplementedImageServer) Annotate(ctx context.Context, req *AnnotateRequest) (*AnnotateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Annotate not implemented")
}

func RegisterImageServer(s *grpc.Server, srv ImageServer) {
	s.RegisterService(&_Image_serviceDesc, srv)
}

func _Image_VideoLatestImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServer).VideoLatestImage(&imageVideoLatestImageServer{stream})
}

type Image_VideoLatestImageServer interface {
	Send(*VideoFrame) error
	Recv() (*VideoFrameRequest, error)
	grpc.ServerStream
}

type imageVideoLatestImageServer struct {
	grpc.ServerStream
}

func (x *imageVideoLatestImageServer) Send(m *VideoFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageVideoLatestImageServer) Recv() (*VideoFrameRequest, error) {
	m := new(VideoFrameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Image_ListStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).ListStreams(m, &imageListStreamsServer{stream})
}

type Image_ListStreamsServer interface {
	Send(*ListStream) error
	grpc.ServerStream
}

type imageListStreamsServer struct {
	grpc.ServerStream
}

func (x *imageListStreamsServer) Send(m *ListStream) error {
	return x.ServerStream.SendMsg(m)
}

func _Image_StartProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).StartProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chrys.cloud.videostreaming.v1beta1.Image/StartProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).StartProxy(ctx, req.(*StartProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_StopProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).StopProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chrys.cloud.videostreaming.v1beta1.Image/StopProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).StopProxy(ctx, req.(*StopProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_Annotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).Annotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chrys.cloud.videostreaming.v1beta1.Image/Annotate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).Annotate(ctx, req.(*AnnotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Image_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chrys.cloud.videostreaming.v1beta1.Image",
	HandlerType: (*ImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProxy",
			Handler:    _Image_StartProxy_Handler,
		},
		{
			MethodName: "StopProxy",
			Handler:    _Image_StopProxy_Handler,
		},
		{
			MethodName: "Annotate",
			Handler:    _Image_Annotate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VideoLatestImage",
			Handler:       _Image_VideoLatestImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ListStreams",
			Handler:       _Image_ListStreams_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "video_streaming.proto",
}
